### ISSUE TITLE
Логирование апишек

### ISSUE THREAD

**Issue by Wudext** [profcomff/.github#106]
Необходимо создать централизованную систему логирования всех логов всех апишек. Логирование будет реализовано через новую библиотеку profcomff_logger.

1) Создать библиотеку, описывающую работу нового логера (profcomff_logger)
1.1) Создание логики работы логера
1.2) Создание базы данных внутри библиотеки
1.3) Создание системы предупреждения об ошибках
2) Использование новой библиотеки во всех апишках

**Comment by grigoriev-semyon** [comment]
Уж не знаю что здесь имелось ввиду, сделано по другому, но к цели вроде пришли
