### ISSUE TITLE
Битая ссылка "Профком студентов ФФ МГУ"

### ISSUE THREAD

**Issue by dyakovri** [profcomff/.github#15]
В кнопках "Обратная связь", "О приложении", "Команда" ссылка "Профком студентов ФФ МГУ" ведёт в никуда.

![Image](https://user-images.githubusercontent.com/51162917/188281294-1c3ef1a4-1086-43a1-bedd-82e6469f34ea.png)

**Comment by Annndruha** [comment]
Пофикшено
