### ISSUE TITLE
Форма обратной связи криво работает

### ISSUE THREAD

**Issue by Annndruha** [profcomff/.github#16]
Форма обратной связи должна слать письма на почту группы profcomff_it@physics.msu.ru
Однако они не доходят. Обсудили с Ромой, сейчас доходят только ему, но это нужно починить.

Как вариант-костыль: продублировать адреса 9 человек из группы в форму.

**Comment by Annndruha** [comment]
Ещё кое-что: нужно исправить "тебя" на "Вас" в заголовке формы

**Comment by dyakovri** [comment]
Смотря как мы относимся к пользователям. Может можно везде тыкать, как в СЦО. А может везде выкать

**Comment by Annndruha** [comment]
Ну, учитывая что приложение "Твой ФФ", а не "Ваш ФФ", то тогда нужно действительно заменять "вас" на "тебя"

**Comment by Annndruha** [comment]
Илья, нужно создать новую форму, где в интеграции прописать вручную адреса почт получателей, поскольку [profcomff_it@physics.msu.ru](mailto:profcomff_it@physics.msu.ru) не работает и изменить ссылку на форму в приложении.

**Comment by Annndruha** [comment]
Отключил пре-модерацию спам сообщений. Теперь в группе не нужно вручную их апрувить. Протетсил.
