### ISSUE TITLE
Изменить QR в описании приложения

### ISSUE THREAD

**Issue by annndruha** [profcomff/.github#25]
Сейчас в QR в центре лого конфы в телеграмме и странный цвет. Подумав, я пришел к выводу, что лучше сделать в центре иконку телеги и qr сделать синим. Чтобы сочеталось с текстовой ссылкой внизу.

**Comment by Annndruha** [comment]
![Screenshot_20230227_211815_Chrome](https://user-images.githubusercontent.com/51162917/221649364-92411793-a5a1-4672-b310-c53796592fc4.jpg)

**Comment by dyakovri** [comment]
https://github.com/profcomff/.github/blob/main/docs/about.md

**Comment by dyakovri** [comment]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/5656720/221652007-811e33dd-a0bf-4a6c-8282-370a3f8442ac.png">
А на компе QR слева
