### ISSUE TITLE
Аппрув нового ТЗ на дизайн

### ISSUE THREAD

**Issue by grigoriev-semyon** [profcomff/.github#37]
ТЗ лежит в РГ
Нужен аппрув по пунктам 1-5, 6й удаляем т.к Паша уже все сверстал

**Comment by dyakovri** [comment]
https://docs.google.com/document/d/1aRSHYJ5FlBbvzgEhZR9HvdFAUdjLm7s_PNcoBpoZZ7k/edit?pli=
