### ISSUE TITLE
Дописать тексты-описания топиков

### ISSUE THREAD

**Issue by Arzangulyan** [profcomff/.github#78]
Что уже есть:

**Бэкэнд**

Про то, как устроен серверный код, как работает всемирная сеть и что такое REST API

Кого тегать с вопросами?
- Про то, как устроены сервисы Твой ФФ @Alevardo и @temmmmo
- Какие бывают сервисы, архитектура кода @dyakov

**Фронтенд**

Чат посвящен разработке пользовательских интерфейсов на веб технологиях. Тут обкашливаем вопросики по HTML, CSS, JavaScript, JS-фреймворкам и другим прелестям жизни в веб браузере

Кого тегать с вопросами?
- Человек-фронтенд, который шарит как устроен Твой ФФ и не только @physphile 
- Про верстку сайтов Артем и @ab1lkosimov 

**Работа с данными**

Обсуждаем подготовку данных, скраппинг и парсинг, системы хранения и способы обработки данных, вне зависимости от размеров и формы

Кого тегать с вопросами?
- Про то, как устроена работа с данными в Твой ФФ @Giga556
- Самый продвинутый инженер данных @alex_ferum
- Про нейросети, машинное обучение и BigData @annndruha

**UI/UX**

Рисуем интерфейсы, обсуждаем юзабилити, проводим UX-исследования, делимся красивыми дизайн системами

Кого тегать с вопросами?
- Иллюстратор всея профкома @rakovao
- Человек, под пером которого рождаются дизайны @pbedrin
- Мастер Figma @yolsha

**Железо**

Микросхемы и печатные платы, пекарни и периферия, принтеры и 3д принтеры – все, что имеет реальное воплощение обсуждаем в этом чате

Кого тегать с вопросами?
- Человеки с паяльниками (в руках) @Cuber_kotleta и @annndruha
- Знает, где найти ту самую железяку @mount0

**DevOps**

Автоматизируем всё и вся! Настраиваем сервера, развёртываем код, изменяем настройки гитхаба

Кого тегать с вопросами?
-  @dyakovri, @Alevardo, @annndruha

**Чат-боты**

Создаём армию ботов чтобы захватить мир! Разработка Telegram, VK и других ботов. Для тех, кому лень писать frontend

Кого тегать с вопросами?
- Заядлые ботоделы @annndruha, @Giga556

**Менеджмент и маркетинг**

Управляем местным IT безобразием, смотрим на метрики, обсуждаем ЦА. Scrum, Agile, ретро, синк, спринт — эти и многие другие термины из жизни PM'а здесь обретают смысл.

Кого тегать с вопросами?
- Управление Твой ФФ и другими проектами в МГУ @MArzangulyan
- Про менеджмент для разработчиков @dyakovri

**Comment by annndruha** [comment]
А это что и где оно будет? EPIC issue чтобы просто висела? Или где-то в доке будет?

**Comment by Arzangulyan** [comment]
@annndruha, это по задумке закрепы в топики чата Вирибуса, чтоб было понятно, кому и по каким вопросам писать

**Comment by annndruha** [comment]
![IMG_20230901_153304_908.jpg](https://github.com/profcomff/.github/assets/51162917/e672d34f-e375-4042-8a26-ce837823e4ba)
